config/routes.rb
Rails.application.routes.draw do
  seems_rateable
  resources :images
  devise_for :users, :controllers => { :registrations => 'registrations' }
  root 'welcome#index'
  get 'my_profile' => 'images#my_images'
  resources :users, only: [:show]
  resources :friendships

  get 'my_friends', to: 'users#my_friends'
  post 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'
  get 'search_for_friends', to: 'users#search_for_friends'
  
  mount Commontator::Engine => '/commontator'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :payment
  accepts_nested_attributes_for :payment
  has_many :images
  has_many :friendships
  has_many :friends, through: :friendships
  acts_as_commontator
  seems_rateable_rater
  
  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "#{email}"
  end
  
  def self.search(param)
    param.strip!
    param.downcase!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end
  
  def self.first_name_matches(param)
    matches('first_name', param)
  end
  
  def self.last_name_matches(param)
    matches('last_name', param)
  end
  
  def self.email_matches(param)
    matches('email', param)
  end
  
  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end
  
  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end
  
  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_friends
    @friendships = current_user.friends
  end
  
  def search_for_friends
    @friendships = current_user.friends
    if params[:search_param].blank?
      flash.now[:danger] = "You have entered an empty search string"
    else
      @users = User.search(params[:search_param])
      @users = current_user.except_current_user(@users)
      flash.now[:danger] = "No users match this search criteria" if @users.blank?
    end
  end
  
  def search
    redirect_to search_for_friends_path(request.parameters)
  end
  
  def add_friend
    @friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: @friend.id)
    
    if current_user.save
      flash[:success] = "Friend was successfully added"
    else
      flash[:danger] = "There was something wrong with the friend request"
    end
    redirect_to my_friends_path
  end

  def show
    @user = User.find(params[:id])
    @users = @user.friends
    @images = @user.images
  end
end

app/views/users/_friends.html.erb
<h3>Friends</h3>
<% if @user.friendships.size > 0 %>
  <table class="table table-striped">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><strong>Name: </strong><%= user.full_name %></td> 
              <td><strong>Email: </strong><%= user.email %></td> 
              <td><strong>Profile: </strong><%= link_to "View profile", user_path(user), class: "btn btn-xs btn-success" %>
                <% if current_user.not_friends_with?(user.id) %>
                  <%= link_to "Add as my friend", add_friend_path(user: current_user, friend: user), 
                    class: "btn btn-xs btn-success", method: :post %>
                <% else %>
                  <span class="label label-primary">
                    You are already friends
                  </span>
                <% end %>
              </td> 
            </tr>
          <% end %>
        </tbody>
      </table>
<% else %>
  <p class="lead">
    <% if current_user == @user %>
      You are
    <% else %>
      This user is 
    <% end %>
    not following anyone
  </p>
<% end %>

app/views/users/my_friends.html.erb
<% if @friendships.size > 0 %>
  <table class="table table-stripped">
    <thead>
      <tr>
        <th colspan="3" class="page-header">
          <h2>My friends</h2>
        </th>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @friendships.each do |friend| %>
        <tr>
          <td><%= friend.full_name %></td>
          <td><%= friend.email %></td>
          <td>
            <%= link_to "View profile", user_path(friend), class: "btn btn-primary btn-xs" %>
            <%= link_to "Remove friend", friendship_path(friend), method: :delete, 
                data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="row col-lg-12">
    <p class="lead">
      You don't have any friends yet. Please add some!
    </p>
  </div>
<% end %>

app/views/users/search_for_friends.html.erb
<%= render 'friends/lookup' %>

app/views/users/show.html.erb
<h2><%= @user.first_name.present? ? @user.first_name : @user.email %>'s Profile</h2>

<h3>Posts</h3>
<% if @user.images.size > 0 %>
  <%= render 'images/show' %>
<% else %>
  <p class="lead">This user has no images uploaded</p>
<% end %>
<%= render 'users/friends' %>