config/routes.rb
Rails.application.routes.draw do
  seems_rateable
  resources :images
  devise_for :users, :controllers => { :registrations => 'registrations' }
  root 'welcome#index'
  get 'my_profile' => 'images#my_images'
  resources :users, only: [:show]
  resources :friendships

  get 'my_friends', to: 'users#my_friends'
  post 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'
  get 'search_for_friends', to: 'users#search_for_friends'
  
  mount Commontator::Engine => '/commontator'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PhotoApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "PhotoShare", root_path, class: "navbar-brand-new"  %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li>
              <div id="friend-lookup">
                <%= form_tag search_friends_path, method: :post, id: "friend-lookup-form" do %>
                  <div class="form-group row no-padding text-center col-md-12">
                    <div class="col-md-10 top-padding">
                      <%=  text_field_tag :search_param, params[:search_param], placeholder: "Search", autofocus: true, 
                                                class: "form-control search-box input-lg" %>
                    </div>
                    <div class="col-md-2 top-padding">
                      <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
                        <i class="fa fa-search"></i> Search
                      <% end %>
                    </div>
                  </div>
                
                <% end %>
              </div>
            </li>
          </ul>
          <ul class="nav navbar-right col-md-4">
            <% if current_user %>
              <li class="dropdown col-md-6 pull-right">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-user"></i><%= current_user.full_name.present? ? current_user.full_name : current_user.email %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "My Profile", my_profile_path  %></li>
                  <li><%= link_to "My Friends", my_friends_path  %></li>
                  <li><%= link_to "Edit Profile", edit_user_registration_path  %></li>
                  <li><%= link_to "Upload Image", new_image_path  %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to('Logout', destroy_user_session_path,
                                class: 'btn btn-xs btn-danger', title: 'Logout', :method => :delete) %></li>
                </ul>
              </li>
            <% else %>
              <li class="col-md-4 pull-right">
                <%= link_to('Sign In', new_user_session_path, class: 'btn btn-primary', title: 'Sign In') %>
              </li>
            <% end %>
          </ul>
          <!--  <ul class="nav navbar-right col-md-4">
            <% if current_user %>
              <li class="col-md-8 user-name">
                <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe,
                                edit_user_registration_path, title: 'Edit Profile' %>
              </li>
              <li class="col-md-1"> </li>
              <li class="col-md-3 logout"><%= link_to('Logout', destroy_user_session_path,
                                class: 'btn btn-xs btn-danger', title: 'Logout', :method => :delete) %></li>
              <% else %>
              <li class="col-md-4 pull-right">
                <%= link_to('Sign In', new_user_session_path, class: 'btn btn-primary', title: 'Sign In') %>
              </li>
            <% end %>
          </ul>-->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <hr>
        <p>&copy; Iulia Gatea 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>